# Use an official Node.js image
FROM node:lts-alpine

# Define a build argument
ARG MODE

# Install a simple HTTP server
RUN npm install -g http-server

# Set the working directory inside the container
WORKDIR /app

# Copy both package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy project files and folders to the container
COPY . .

# Build the app based on the specified mode
RUN if [ "$MODE" = "development" ]; then npm run build:dev; \
    elif [ "$MODE" = "uat" ]; then npm run build:uat; \
    else echo "Error: Unsupported mode $MODE"; exit 1; fi

# Expose port 8080 for the HTTP server
EXPOSE 8080

# Command to run the HTTP server and serve the app
CMD ["http-server", "dist"]
